"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.RulesPage = void 0;
const React = __importStar(require("react"));
require("./css/rules.css");
const RulesPage = () => {
    return (React.createElement(React.Fragment, null,
        React.createElement("section", { className: "container" },
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-xs-2" },
                    React.createElement("div", { className: "rules-nav" },
                        React.createElement("h1", null, "Rules"),
                        React.createElement("ul", { className: "nav nav-pills nav-stacked" },
                            React.createElement("li", null,
                                React.createElement("a", { href: "/rules#lobby-and-rooms" }, "Lobby and Rooms")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "/rules#game-settings" }, "Game Settings")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "/rules#game-basics" }, "Game Basics")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "/rules#drawing-basics" }, "Drawing Basics")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "/rules#guessing-basics" }, "Guessing Basics")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "/rules#using-the-toolbox" }, "Using the Toolbox"))))),
                React.createElement("div", { className: "col-xs-10" },
                    React.createElement("div", { id: "lobby-and-rooms", className: "col-md-12 rules-anchor" },
                        React.createElement("h1", null, "Lobby and Rooms"),
                        React.createElement("div", { className: "thumbnail" },
                            React.createElement("div", { className: "caption" },
                                React.createElement("blockquote", null,
                                    React.createElement("b", null, "The lobby has a list of rooms."),
                                    " A separate game is held in each room.")))),
                    React.createElement("div", { id: "game-settings", className: "col-md-12 rules-anchor" },
                        React.createElement("h1", null, "Game Settings"),
                        React.createElement("div", { className: "thumbnail" },
                            React.createElement("div", { className: "caption" },
                                React.createElement("blockquote", null,
                                    React.createElement("p", null,
                                        React.createElement("b", null, "The host has 5 settings "),
                                        " to pick before the game starts.")),
                                React.createElement("ul", { className: "media-list" },
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" }),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The topic."),
                                            React.createElement("b", null, "This is the theme of the prompts."))),
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" }),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The difficulty."),
                                            React.createElement("b", null, "This sets how difficult the prompts will be to draw and guess."),
                                            " ",
                                            "The random option will select prompts from all of the difficulties.")),
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" }),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The number of rounds."),
                                            React.createElement("b", null, "The number of rounds before the game ends."))),
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" }),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The drawing timer."),
                                            React.createElement("b", null, "This sets how much time the drawer gets to draw. "),
                                            " If no one guesses their drawing during this time, the round will end.")),
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" }),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The reserve timer."),
                                            React.createElement("b", null, "when the first person correctly guesses the prompt, the timer will swap to reserve time."),
                                            " ",
                                            "The rest of the guessers have this much time to guess before the round ends.")))))),
                    React.createElement("div", { id: "game-basics", className: "col-md-12 rules-anchor" },
                        React.createElement("h1", null, "Game Basics"),
                        React.createElement("div", { className: "thumbnail" },
                            React.createElement("img", { src: "modules/client/rules/img/round.png", alt: "The round number is displayed above the canvas." }),
                            React.createElement("div", { className: "caption" },
                                React.createElement("blockquote", null,
                                    React.createElement("b", null, "Each game is made up of a number of rounds."),
                                    " Each round has a drawer."),
                                "The current round and current drawer are displayed in the middle column of the game page.")),
                        React.createElement("div", { className: "thumbnail" },
                            React.createElement("img", { src: "modules/client/rules/img/players.png", alt: "In this room there are 3 players: 1 drawer and 2 guessers." }),
                            React.createElement("div", { className: "caption" },
                                React.createElement("blockquote", null,
                                    "The player list shows the usernames and points of all the players in the room.",
                                    React.createElement("b", null, "After the last round, the player with the most points wins!")),
                                "In the player list, the drawer's username is bolded.",
                                React.createElement("sup", null, "1"),
                                " ",
                                "All other players in the room are guessers. If a guesser makes a correct guess a tick will show up to the left of their score.",
                                React.createElement("sup", null, "2"),
                                "The drawer changes each round according to the order in the player list. The player list also shows the number of points each user has to the right of their username. The current and maximum number of players is displayed at the top of the player list."))),
                    React.createElement("div", { id: "drawing-basics", className: "col-md-12 rules-anchor" },
                        React.createElement("h1", null, "Drawing Basics"),
                        React.createElement("div", { className: "thumbnail" },
                            React.createElement("img", { src: "modules/client/rules/img/drawer.png", alt: "The drawer tries to draw a drain on the canvas." }),
                            React.createElement("div", { className: "caption" },
                                React.createElement("blockquote", null,
                                    React.createElement("p", null,
                                        React.createElement("b", null,
                                            "The drawer will be given a prompt that only they can see",
                                            React.createElement("sup", null, "1")),
                                        ", and have a set time to draw the prompt on the canvas. If no one guesses their drawing during this time, the round will end.",
                                        React.createElement("sup", null, "2"))),
                                "Drawers are not allowed to write letters or numbers. In general, drawers should just draw the prompt instead of trying to get around restrictions. However, it is acceptable to split compound words into individual words. For example when given the prompt \"paper boat\", one could draw paper, a plus sign, and a boat. Ultimately, the rules are enforced by the room host rather than the game. If players disagree with the rules of the host, they are encouraged to host their own room."))),
                    React.createElement("div", { id: "guessing-basics", className: "col-md-12 rules-anchor" },
                        React.createElement("h1", null, "Guessing Basics"),
                        React.createElement("div", { className: "thumbnail" },
                            React.createElement("img", { src: "modules/client/rules/img/timer.png", alt: "The second timer goes to red after the first person guesses correctly." }),
                            React.createElement("div", { className: "caption" },
                                React.createElement("blockquote", null,
                                    React.createElement("p", null,
                                        React.createElement("b", null, "After the first user guesses correctly, all the other guessers must guess in a set time before the round ends."),
                                        " ",
                                        "The top timer will stop and the bottom one will start.")))),
                        React.createElement("div", { className: "thumbnail" },
                            React.createElement("img", { src: "modules/client/rules/img/guess.png" }),
                            React.createElement("div", { className: "caption" },
                                React.createElement("blockquote", null,
                                    React.createElement("p", null,
                                        React.createElement("b", null, "Guessers can make guesses in the guess box"),
                                        " while the drawer is drawing.")),
                                "All players can see what the guesses are, unless a guess is close to the prompt. If the guess is close to the prompt, the person who made that guess will be notified that they are close, and their guess only visible to them and the drawer. When the prompt is guessed correctly, the drawer and the person who guessed correctly will each get N-1 points, where N is the number of players in the room. If there the remaining time of the round was greater than 20 seconds, it will be reduced to 20 seconds. The drawer will receive an additional point for each guesser who guesses correctly after the first, and those guessers will receive one point less than the person who guessed correctly before them.",
                                React.createElement("br", null),
                                "Drawers can pass the round if they do not wish to draw. This cannot be used if someone has already guessed the prompt."))),
                    React.createElement("div", { id: "using-the-toolbox", className: "col-md-12 rules-anchor" },
                        React.createElement("h1", null, "Using the Toolbox"),
                        React.createElement("div", { className: "thumbnail" },
                            React.createElement("img", { src: "modules/client/rules/img/toolbox.png" }),
                            React.createElement("div", { className: "caption" },
                                React.createElement("blockquote", null,
                                    React.createElement("p", null,
                                        React.createElement("b", null, "The drawer has 5 different types of tools"),
                                        " at their disposal.")),
                                React.createElement("ul", { className: "media-list" },
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" },
                                            React.createElement("img", { className: "media-object", src: "modules/client/rules/img/toolbox1.png", alt: "The brush and eraser tool." })),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The brush and eraser tool."),
                                            React.createElement("b", null, "You can switch between the brush and the eraser tool using these buttons."),
                                            "The brush tool lets you draw on the canvas and the eraser tool lets you remove parts of your drawing.")),
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" },
                                            React.createElement("img", { className: "media-object", src: "modules/client/rules/img/toolbox2.png", alt: "The size slider." })),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The size slider."),
                                            React.createElement("b", null, "The size slider lets you choose the size of your brush or eraser."),
                                            " ",
                                            "Moving the slider to the left makes your tool smaller whereas moving it to the right makes it larger.")),
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" },
                                            React.createElement("img", { className: "media-object", src: "modules/client/rules/img/toolbox3.png", alt: "The colour palette." })),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The colour palette."),
                                            React.createElement("b", null, "The colour palette gives you 15 different colours to paint with."),
                                            " ",
                                            "If you hover over each colour, a tooltip will pop up telling you the name of the colour you're hovering over.")),
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" },
                                            React.createElement("img", { className: "media-object", src: "modules/client/rules/img/toolbox4.png", alt: "The custom colour tool." })),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The custom colour tool."),
                                            React.createElement("b", null, "The custom colour tool lets you choose your own colour!"),
                                            " ",
                                            "Click on the custom colour button to bring up the colour selection pop up.")),
                                    React.createElement("li", { className: "media" },
                                        React.createElement("div", { className: "media-left" },
                                            React.createElement("img", { className: "media-object", src: "modules/client/rules/img/toolbox5.png", alt: "The clear canvas button." })),
                                        React.createElement("div", { className: "media-body" },
                                            React.createElement("h4", { className: "media-heading" }, "The clear canvas button."),
                                            React.createElement("b", null, "This button lets you clear the entire canvas."))))))))))));
};
exports.RulesPage = RulesPage;
